language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_script:
  - cd ./src

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  -  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=HonoR974_P9
  - mvn clean verify -P test-business
  - cd ../docker/dev
  - docker-compose up -d
  - cd ../../src

addons:
  sonarcloud:
    organization: "honor974"
    token:
      secure: aecf2362c158c5f7120baa41c4bc7074394b5ec3 # encrypted value of your token

