language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_script:
  - cd ./src

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  -  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify -P test-consumer,test-business sonar:sonar -Dsonar.login=f40b92dc7a927178a8234e64dd63911a19728682
  - cd ../docker/dev
  - docker-compose up -d
  - cd ../../src

addons:
  sonarcloud:
    organization: "honor974"
    token:
      secure: f40b92dc7a927178a8234e64dd63911a19728682 # encrypted value of your token

