language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "honor974"
    token:
      secure: "7b856c7363162d467048a1ea91f893851c2a0922" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis

  - cd docker/dev
  - docker-compose up -d
  - cd ../../src
 - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=HonoR974_P9
# - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
