language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_script:
  - cd ./src

script:
  - mvn clean verify -P test-business
  - cd ../docker/dev
  - docker-compose up -d
  - cd ../../src
